### ISSUE TITLE
I don't have an user called Plex or video group

### ISSUE THREAD

**Issue by ThierryBegin** [kern2011/Freenas-Quicksync#1]
one of the steps 
`pw groupmod -n video -m plex`
doesn't work for me since it seem I have no user or group named like that. I installed plex from the plugin section.

**Comment by thorsteneb** [comment]
A bespoke jail with the plexmediaserver package installed will definitely have a "plex" user, as well. My bet is @ThierryBegin missed the part of the instructions that says "in a jail shell", and didn't "iocage console plex" before trying the pw groupmod command.

**Comment by ThierryBegin** [comment]
@thorsteneb no, Im surely in the plex jail. not sure why it is that way but seem there is a lot of missing user when I do a 
awk -F":" '{print $1}' /etc/passwd
I reinstalled everything and now I have all the users. I haven't gone further in the config for now since quicksync might not be enough for what I want to transcode. I more planning on having a secondary computer with a nvidia card in it .

anyway, we can close this issue now
