### ISSUE TITLE
Support for Emby

### ISSUE THREAD

**Issue by giacrossi** [kern2011/Freenas-Quicksync#10]
Hi,

Does your script support only Plex? The only mention to Plex is the command `[plex_drm=5]` so I'm wondering if I can use that script, changing plex_drm with emby_drm in my emby jail. It seems that the other commands are generic and don't concern the underneath server.

**Comment by thorsteneb** [comment]
Emby doesn't support hardware transcode on FreeBSD currently. Once it does, that can be tested on FreeNAS.
