### ISSUE TITLE
Needed to install Intel drivers and rename libraries in Plex Jail to get this to work

### ISSUE THREAD

**Issue by justinemerson** [kern2011/Freenas-Quicksync#13]
My system: FreeNAS 11.3U4.1 running on an i5-4690K in a Gigabyte Z97M-Gaming-5 motherboard, using an HDMI dummy dongle.

I had to follow some of the additional steps outlined in this Plex forum thread:

https://forums.plex.tv/t/enable-hardware-acceleration-support-for-bsd-based-plex-servers/236120/104

Specifically, I had to:
install the intel-driver and intel-media-driver  packages in the Plex Jail
I had to copy the driver files into the /usr/local/share/plexmediaserver-plexpass/lib/dri folder  (they were not there)
I had to rename the various libraries that were included in the plexpass/lib folder that are obsoleted by newer ones in the Jail's /usr/local/lib folder.

Once I did that it started working.

**Comment by thorsteneb** [comment]
That sounds like a Plex-specific issue. I'd take it up in the forums there so it can be fixed in a future version.

**Comment by justinemerson** [comment]
Yes it's Plex specific, but this entire article is about getting Plex to work. Plex has said they aren't supporting 11.3 of FreeBSD, only 12.0, so no point in complaining.
