### ISSUE TITLE
Panic when running "kldload" command

### ISSUE THREAD

**Issue by bougs93** [kern2011/Freenas-Quicksync#3]
Version:  FreeNAS-11.3-U1
intel CPU : j4105

When I run the command it reboots.
" kldload /boot/modules/i915kms.ko "

I get a panic and can't:

I will wait until the FreeNAS 12 version is released.

**Comment by thorsteneb** [comment]
Interesting. If you're really curious, you can always see how this behaves in TrueNAS Core 12.0 / FreeBSD 12.1, and then get back to FreeNAS 11.3U1 via boot environment. "Take a config backup" etc., of course, and be aware you're testing, not running for production.
