### ISSUE TITLE
can't find dri & drm

### ISSUE THREAD

**Issue by mrMuppet** [kern2011/Freenas-Quicksync#4]
I did everything written in your tutorial but not the downgrade to libva2.5 . 
Installed new Plex version 1.18.8.2468 . But i can't find the dri and drm in dev. In the plex-jail i find drm.ko and i915kms.ko via kldstat. 

Any idea?

btw. the dates in your readme are little confusing... 2019/2020 dd/mm vs mm/dd

**Comment by thorsteneb** [comment]
I'm not so clear that a github issue is the right place to troubleshoot your setup. I invite you to troubleshoot over on the FreeNAS forums, though: https://www.ixsystems.com/community/threads/activating-plex-hardware-acceleration.75391/page-4

Any troubleshooting will, at a minimum, require: Hardware, FreeNAS version, Plex version, ls /dev/dri on FreeNAS, ls /dev/dri in Plex iocage jail.
