### ISSUE TITLE
More clarification on Core CPUs and C222, C232, C242 chipsets

### ISSUE THREAD

**Issue by giacrossi** [kern2011/Freenas-Quicksync#9]
Hi, I need a better clarification about Intel Core CPUs and these chipsets: is it possible to use Quicksync by means of integrated GPU or not?

**Comment by thorsteneb** [comment]
Nope. Cxx6 chipsets only.

**Comment by thorsteneb** [comment]
Take a look at the outstanding PR and let me know whether that clarifies the guidance sufficiently
